<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="description">
        <meta content="" name="author">
        <title>
            Data and Analytics | Miracle
        </title>
        <link href="../css/bootstrap.min.css" rel="stylesheet">
        <link href="../css/font-awesome.min.css" rel="stylesheet">
        <link href="../css/main.css" rel="stylesheet">
        <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
        <link href="../css/default.css" rel="stylesheet" type="text/css">
        <link href="../css/component.css" rel="stylesheet" type="text/css">
        <script src="js/modernizr.custom.js"></script><!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="../images/favicon.ico" rel="shortcut icon">
        <style>
            .tinted-image {
         background: 
         /* top, transparent red */
         linear-gradient(
         rgba(0, 0, 0, 0.55), 
         rgba(0, 0, 0, 0.55)
         ),
         /* your image */
         url("../images/technologies/data-analysis.png");
         -webkit-background-size: cover;
         -moz-background-size: cover;
         -o-background-size: cover;
         background-size: cover;
         }
         .breadcrumb {margin:0px !important;}
         .breadcrumb li,.breadcrumb li a{color:#FFF !important;}
         .text-dark, .text-dark:hover, a.text-dark, a.text-dark:hover, a.text-dark:focus {
         background-color: #232527;
         color:#fff;
         }
         .card {border:0px !important;} 
         .emerald{background-color:#0d416b !important;width:100%;}
        </style>
    </head><!--/head-->
  <?php include '../header.php';?>
    <body>
        <section id="services" >
         <br>
         <br>
     
         <div class="emerald tinted-image">
            <div class="container ">
               <div class="row">
                  <br><br><br>
                  <div class="col-sm-6 text-left">
                     <h1 class="heavy micro"> Data and Analytics</h1>
                  </div>
				  <br>
                  <div class="col-sm-6 text-right">
                     <ul class="breadcrumb pull-right">
                        <li><a href="../">Home</a></li>
                        <li><a href="../technologies/">Technologies</a></li>
                        <li class="active">Data and Analytics</li>
                     </ul>
                  </div>
               </div>
            </div>
           <br>
      </section>
      <br>
        <section class="container" id="about-us">
            
            <div class="row">
                
                <div class="col-sm-12">
                    <br>
                    <p class="methodText">
                        With the emergence of Mobile and Social, the amount of data being generated by IT systems has soared. Users around the world are generating heterogeneous and raw data every second. A user at a grocery store is generating preference data during his billing. A girl buying her wedding dress, is posting preference data onto Social. Data is everywhere and it is time enterprises leverage this data to accelerate business growth.
                    </p>
                    <p class="methodText">
                        When this data is put to proper use it helps to provide better insight into customer behaviour and gives you the ability to take proactive decisions. You can repair a washing machine even before it stops working by using predictive analytics and hence provide a richer customer experience. All this transactional data has to be stored somewhere and in turn has to be analyzed and put to proper use. Our Data teams at Miracle help you to manage your data effectively and in turn gain insights into data patterns.
                    </p>
                    <p class="methodText">
                        <strong>Miracle Data Services Practice provides several services ranging from,</strong>
                    </p>
                    <div class="row">
                        <div class="col-sm-4">
                            <ul>
                                <li>Database Administration Services
                                </li>
                                <li>Database Migration Services
                                </li>
                                <li>Data Extraction Services(ETL)
                                </li>
                            </ul>
                        </div>
                        <div class="col-sm-4">
                            <ul>
                                <li>Data Quality Services
                                </li>
                                <li>Master Data Management Services
                                </li>
                                <li>Data Warehousing Services
                                </li>
                            </ul>
                        </div>
                        <div class="col-sm-4">
                            <ul>
                                <li>Business Intelligence
                                </li>
                                <li>Reporting Services
                                </li>
                            </ul>
                        </div>
                    </div>
                    <p class="methodText">
                        <strong>Database Expertise</strong>
                    </p>
                    <div class="row">
                        <div class="col-sm-3">
                            <ul>
                                <li>IBM DB2
                                </li>
                                <li>Oracle
                                </li>
                            </ul>
                        </div>
                        <div class="col-sm-3">
                            <ul>
                                <li>SSIS and SSRS
                                </li>
                                <li>MySQL
                                </li>
                            </ul>
                        </div>
                        <div class="col-sm-3">
                            <ul>
                                <li>MS SQLServer
                                </li>
                                <li>Cloudant(NoSQL)
                                </li>
                            </ul>
                        </div>
                        <div class="col-sm-3">
                            <ul>
                                <li>Mongodb
                                </li>
                            </ul>
                        </div>
                      
                    </div>
                    <p class="methodText">
                        <strong>Analytic Expertise</strong>
                    </p>
                    <div class="row">
                        <div class="col-sm-2">
                            <ul>
                                <li>IBM Cognos
                                </li>
                            </ul>
                        </div>
                        <div class="col-sm-2">
                            <ul>
                                <li>Tableau
                                </li>
                            </ul>
                        </div>
                        <div class="col-sm-2">
                            <ul>
                                <li>Hadoop
                                </li>
                            </ul>
                        </div>
                        <div class="col-sm-3">
                            <ul>
                                <li>Google Analytics
                                </li>
                            </ul>
                        </div>
                        <div class="col-sm-3">
                            <ul>
                                <li>QilkView/QlikSense
                                </li>
                            </ul>
                        </div>
                        
                    </div>
                    <p>
                        With petabytes of data out there, it is time you started leveraging it to your advantage. For more information on <strong>Data and Analytics</strong>, contact us at <a class="linkText" href="mailto:data@miraclesoft.com"><strong style="text-decoration: underline">data@miraclesoft.com</strong></a>
                    </p>
                </div>
                
            </div><br>
            <br>
        </section><!--/#about-us-->
        <?php include '../footer.php';?>
    </body>
</html>